export const REALTIME_PROVIDER = Symbol('REALTIME_PROVIDER');
export const REALTIME_CONFIG = Symbol('REALTIME_CONFIG');
export const REALTIME_AUTH_PROVIDER = Symbol('REALTIME_AUTH_PROVIDER');
export const REALTIME_PRESENCE = Symbol('REALTIME_PRESENCE');
export const REALTIME_SERIALIZER = Symbol('REALTIME_SERIALIZER');
export const REALTIME_METRICS = Symbol('REALTIME_METRICS');
