export const REPORT_EXPORT_PORT = Symbol('REPORT_EXPORT_PORT');
export const REPORT_STORAGE_PROVIDER = Symbol('REPORT_STORAGE_PROVIDER');
export const REPORT_QUEUE_ADAPTER = Symbol('REPORT_QUEUE_ADAPTER');
export const REPORT_SCHEDULER = Symbol('REPORT_SCHEDULER');
